# An example of ClusterConfig object using Managed Nodes
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-lab-k8cluster
  region: us-east-2

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: k8s-admin
      labels: { aws-usage: "lab-cluster-ops" }
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AdministratorAccess

managedNodeGroups:
  - name: base-nodegroup
    spot: true
    minSize: 2
    desiredCapacity: 2
    maxSize: 2
    availabilityZones: ["ca-central-1a", "ca-central-1b"]
    volumeSize: 20
    labels: {role: worker}
    tags:
      nodegroup-role: kube-system-worker
    iam:
      withAddonPolicies:
        albIngress: true
        externalDNS: true
        certManager: true
        ebs: true

cloudWatch:
  clusterLogging:
    enableTypes: ["all"]